name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
           node-version: '20'

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Generate CHANGELOG.md
        run: conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Read changelog
        id: changelog
        run: |
          $notes = Get-Content CHANGELOG.md | Out-String
          echo "release_notes<<EOF" >> $env:GITHUB_ENV
          echo "$notes" >> $env:GITHUB_ENV
          echo "EOF" >> $env:GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore src/LiveMarkdown.Avalonia/LiveMarkdown.Avalonia.csproj

      - name: Build
        run: dotnet build src/LiveMarkdown.Avalonia/LiveMarkdown.Avalonia.csproj --configuration Release --no-restore

      - name: Pack
        run: |
          $year = (Get-Date).Year
          $version = "${{ github.ref_name }}" -replace '^v',''
          if ($year -eq 2025) {
            $copyright = "Copyright 2025 DearVa"
          } else {
            $copyright = "Copyright 2025-$year DearVa"
          }
          dotnet pack src/LiveMarkdown.Avalonia/LiveMarkdown.Avalonia.csproj --configuration Release --no-build -p:PackageVersion=$version -p:Copyright="$copyright" -p:PackageReleaseNotes="${{ env.release_notes }}" -o ${{ github.workspace }}/out

      - name: Publish to NuGet
        run: |
          $pkg = Get-ChildItem "${{ github.workspace }}/out/*.nupkg" | Select-Object -First 1
          if ($null -eq $pkg) { throw 'No nupkg found!' }
          dotnet nuget push $pkg.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
